@startuml Clínica Médica

left to right direction
skinparam actorStyle awesome

actor "Paciente" as paciente
actor "Sistema de E-mail" as email

rectangle "Sistema Clínica Médica" {
    usecase "Agendar Consulta" as UC1
    usecase "Cancelar Consulta" as UC2
    usecase "Enviar E-mail de Confirmação" as UC3
    usecase "Enviar E-mail de Cancelamento" as UC4
}

paciente --> UC1
paciente --> UC2

UC1 ..> UC3 : <<include>>
UC2 <.. UC4 : <<extend>>

UC3 --> email
UC4 --> email

@enduml
